; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
build_dir = C:/tmp/pio-build/auto-toilet

[env:m5stack-grey]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = m5stack-grey
framework = arduino
monitor_speed = 115200
build_flags =
	-D MQTT_MAX_PACKET_SIZE=512
lib_deps =
	m5stack/M5Unified @ ^0.2.2
	ncmreynolds/ld2410
	https://github.com/m5stack/M5Unit-AudioPlayer.git
	crankyoldgit/IRremoteESP8266 @ ^2.9.0
	knolleary/PubSubClient @ ^2.8
